language: node_js
dist: xenial
os: linux
node_js: 17

env:
  jobs:
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

stages:
  - name: 'test'
    if: |
      tag IS blank

jobs:
  include:
    - stage: 'test'
      name: 'NodeJS "stable"'
      script: npm test
